### PR TITLE
Update anonymizer.txt

### PR DESCRIPTION
**Pull request by Jerome2103**
add New URL

### CODE REVIEW

**Comment by Jerome2103** [comment]
Here the test links

- https://anonym.to/?https://github.com/Tautulli/tautulli.github.io
- https://www.lolinez.com/?https://github.com/Tautulli/tautulli.github.io
- https://href.li/?https://github.com/Tautulli/tautulli.github.io
- https://dereferer.me/?https://github.com/Tautulli/tautulli.github.io
- https://url.rw/?https://github.com/Tautulli/tautulli.github.io
- http://nullrefer.ir/?https://github.com/Tautulli/tautulli.github.io

**Comment by JonnyWong16** [comment]
No, it only works with one URL.

I also don't like any of those because they have a landing page instead of redirecting immediately.

**Comment by Jerome2103** [comment]
But https://href.li/? redirect immediately? the same 
https://nullreferer.com/?

**Comment by JonnyWong16** [comment]
Still only works with one URL.

**Pull request closed without merging**
